language: java
jdk:
- oraclejdk8
script:
- "./gradlew -i clean ass fat"
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: ckqqB90F64WsAispDzBpDSkmxM7d2W3uZD4eywXFMyeznJugQtlxsPZxJ2HQZIBD6eKGUXM0rkfTyTIGp6GXFmW9tUxSCEAWfAtIYBQhpOlTMivDFnnUFDaUKe+YZ88J3YwgLvkJUQI6Jz6SuSMr6NvSClZ/EXG5OSRI74RYSJi1DZ7Agt6oF9eyREi84FSqaiUS35PqNAdZs2Q2+/PAYZor4Rm/gWUpQOFb10NUr/X8NGC6oqptIojOxhYhKDPvSXnKj1T5u806pbifBJJJ4mBQzln5XlSyC0Rg1gujb0UxOVVQPHwloIS1MR5jRyq5in+6QaMaz6Qu1UxRksbMMH/eWo1d8jp2rkJeXPh/zpittYbTbeaZBWNlMf+0XfMWGwRuPbJyL48mlgkQG7aDcz1qt6byvLCFgF2EwSC2ZdPMI+8q7vVRJLMrjMiZ3nwFE9CqIOjQxZW44Vyr2+GFWedzR4BvH1p6HywWM1kGoGX5WGSG63KDzOqjAl1w7AWyAwK4jjeiGFTWJESNYOu5+3ZTDSekjbJSNM7Sbxy1HVp2dcjV+k36xU3Qw9v/wzuNy0r4Nfb3DaIJVk06/9PPy6vnA0Trbz9d6E3y//VGzQXZV4KHuORXRJjnaIGwwoQB1Cu9L+AJbf102g0B5uVMGd5Dgzbj7G9OdDjixisv1z4=
  file: build/libs/ByteCartRedux-*.jar
  file_glob: true
  on:
    tags: true
